### ISSUE TITLE
seg fault on linux

### ISSUE THREAD

**Issue by turnert74** [fuze/soleng-call-recordings-downloader-public#1]
I have tried running cli-linux on fedora and centos

Linux redacted 5.5.13-200.fc31.x86_64 #1 SMP Wed Mar 25 21:55:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Linux redacted 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ifrias-fuze** [comment]
This is an issue with the underlying library used to package the binary. ( https://github.com/zeit/pkg/issues/753).

The workaround at this time would be to either run the code directly or build the binary on the target OS.
